/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import visao.interna.CadastroCidade;
import visao.interna.CadastroOperadora;
import visao.interna.EditarServico;
import visao.interna.ImportarServico;

/**
 *
 * @author yuri.miyazaki
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mCadastroOperadora = new javax.swing.JMenuItem();
        mCadastroCidade = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mImportarServico = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mEditarServico = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        mCadastroOperadora.setText("Operadora");
        mCadastroOperadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroOperadoraActionPerformed(evt);
            }
        });
        jMenu1.add(mCadastroOperadora);

        mCadastroCidade.setText("Cidade");
        mCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(mCadastroCidade);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Importar");

        mImportarServico.setText("Serviço");
        mImportarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mImportarServicoActionPerformed(evt);
            }
        });
        jMenu2.add(mImportarServico);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Editar");

        mEditarServico.setText("Serviço");
        mEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEditarServicoActionPerformed(evt);
            }
        });
        jMenu3.add(mEditarServico);

        jMenuBar1.add(jMenu3);

        mSair.setText("Sair");
        mSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSairMouseClicked(evt);
            }
        });
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroCidadeActionPerformed
        CadastroCidade tela = new CadastroCidade();
        areaTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mCadastroCidadeActionPerformed

    private void mCadastroOperadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroOperadoraActionPerformed
        CadastroOperadora tela = null;
        try {
            tela = new CadastroOperadora();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        areaTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mCadastroOperadoraActionPerformed

    private void mImportarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mImportarServicoActionPerformed
        ImportarServico tela = new ImportarServico();
        areaTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mImportarServicoActionPerformed

    private void mEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEditarServicoActionPerformed
        EditarServico tela = new EditarServico();
        areaTrabalho.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_mEditarServicoActionPerformed

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed

    }//GEN-LAST:event_mSairActionPerformed

    private void mSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_mSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mCadastroCidade;
    private javax.swing.JMenuItem mCadastroOperadora;
    private javax.swing.JMenuItem mEditarServico;
    private javax.swing.JMenuItem mImportarServico;
    private javax.swing.JMenu mSair;
    // End of variables declaration//GEN-END:variables
}
