/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.interna;

import controle.ControleCidade;
import javax.swing.DefaultComboBoxModel;
import modelo.Cidade;

/**
 *
 * @author yuri.miyazaki
 */
public class CadastroCidade extends javax.swing.JInternalFrame {
        String vazio[] = {"Selecione"};
        String norte[] = {"Selecione","Tocantins","Acre","Pará","Rondônia","Roraima","Amapá","Amazonas"};
        String centroOeste[] = {"Selecione","Mato Grosso","Mato Grosso do Sul","Goiás ","Distrito Federal"};
        String nordeste[] = {"Selecione","Bahia","Sergipe","Alagoas","Paraíba","Pernambuco","Rio Grande do Norte","Ceará","Piauí","Maranhão"};
        String sudeste[] = {"Selecione","Espírito Santo","Rio de Janeiro","Minas Gerais","São Paulo"};
        String sul[] = {"Selecione","Santa Catarina","Rio Grande do Sul","Paraná"};
        String Regiao[] = {"Selecione","Norte","Centro-Oeste","Nordeste","Sudeste","Sul"};
        
    /**
     * Creates new form CadastrarCidade
     */
    public CadastroCidade() {
        initComponents();
        cbRegiao.setModel(new DefaultComboBoxModel(Regiao));
        cbEstado.setModel(new DefaultComboBoxModel(vazio));
        cbCodigo.setModel(new DefaultComboBoxModel(vazio));
        
        
        for(int i = 1; i < 100; i++){
            cbCodigo.addItem(Integer.toString(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbRegiao = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        cbCodigo = new javax.swing.JComboBox<>();
        btCadastrar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        txtCidade = new javax.swing.JTextField();

        jLabel1.setText("Cadastrar Cidade");

        jLabel2.setText("Região");

        jLabel3.setText("Estado");

        jLabel4.setText("Codigo");

        jLabel5.setText("Cidade");

        cbRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRegiaoActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCidade)
                            .addComponent(cbRegiao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbRegiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(cbEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btFechar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void cbRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRegiaoActionPerformed
        if(cbRegiao.getSelectedItem() == "Norte"){
            cbEstado.setModel(new DefaultComboBoxModel(norte));
        }else{
            if(cbRegiao.getSelectedItem() == "Centro-Oeste"){
                cbEstado.setModel(new DefaultComboBoxModel(centroOeste));
            }else{
                if(cbRegiao.getSelectedItem() == "Nordeste"){
                    cbEstado.setModel(new DefaultComboBoxModel(nordeste));
                }else{
                    if(cbRegiao.getSelectedItem() == "Sudeste"){
                        cbEstado.setModel(new DefaultComboBoxModel(sudeste));
                    }else{
                        if(cbRegiao.getSelectedItem() == "Sul"){
                            cbEstado.setModel(new DefaultComboBoxModel(sul));
                        }else{
                            cbEstado.setModel(new DefaultComboBoxModel(vazio));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_cbRegiaoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        
        Cidade novaCidade = new Cidade();
        novaCidade.Inserir((String)cbRegiao.getSelectedItem(), (String)cbEstado.getSelectedItem(),Integer.parseInt((String)(cbCodigo.getSelectedItem())), txtCidade.getText());
        
        ControleCidade cadastrarCidade = new ControleCidade();
        
        if(cadastrarCidade.Cadastrar(novaCidade)){
            System.out.println("Cadastrado");
        }else{
            System.out.println("Não Cadastrado");
        }
        
        
        
        
    }//GEN-LAST:event_btCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btFechar;
    private javax.swing.JComboBox<String> cbCodigo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbRegiao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCidade;
    // End of variables declaration//GEN-END:variables
}
