/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.interna;

import controle.ControleArquivoReclamacao;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.ArquivoReclamacao;
import modelo.No;
import modelo.ReclamacaoTableModel;

/**
 *
 * @author yuri.miyazaki
 */
public class ImportarServico extends javax.swing.JInternalFrame {

    ReclamacaoTableModel jTReclamacao = new ReclamacaoTableModel();
    
    
    /**
     * Creates new form ImportarServico
     */
    public ImportarServico() {
        initComponents();
        tblReclamacao.setModel(jTReclamacao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCaminhoArquivo = new javax.swing.JTextField();
        btSelectArquivo = new javax.swing.JButton();
        opQualidade = new javax.swing.JRadioButton();
        opReclamacao = new javax.swing.JRadioButton();
        btImportar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReclamacao = new javax.swing.JTable();
        btListar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        jLabel1.setText("Imporatar Arquivo de Serviço");

        jLabel2.setText("Arquivo");

        txtCaminhoArquivo.setEditable(false);
        txtCaminhoArquivo.setText("C:\\Users\\a_nin\\Downloads\\Pi III\\Arquivo de importação\\Solicitações Registradas na Anatel (2006-ES).csv");

        btSelectArquivo.setText("...");
        btSelectArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectArquivoActionPerformed(evt);
            }
        });

        opQualidade.setSelected(true);
        opQualidade.setText("Qualidade");
        opQualidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opQualidadeActionPerformed(evt);
            }
        });

        opReclamacao.setText("Reclamaçao");
        opReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReclamacaoActionPerformed(evt);
            }
        });

        btImportar.setText("Importar");
        btImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImportarActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        tblReclamacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblReclamacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReclamacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReclamacao);

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btListar))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opQualidade)
                                .addGap(18, 18, 18)
                                .addComponent(opReclamacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                                .addComponent(btImportar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCaminhoArquivo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSelectArquivo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSelectArquivo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImportar)
                    .addComponent(btFechar)
                    .addComponent(opQualidade)
                    .addComponent(opReclamacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void opReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReclamacaoActionPerformed
        opQualidade.setSelected(false);
        opReclamacao.setSelected(true);
    }//GEN-LAST:event_opReclamacaoActionPerformed

    private void opQualidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opQualidadeActionPerformed
        opReclamacao.setSelected(false);
        opQualidade.setSelected(true);
    }//GEN-LAST:event_opQualidadeActionPerformed

    private void btSelectArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectArquivoActionPerformed
        JFileChooser arquivo = new JFileChooser();
        FileNameExtensionFilter arquivoCSV = new FileNameExtensionFilter("Arquivos CSV", "csv"); 
        arquivo.addChoosableFileFilter(arquivoCSV);
        arquivo.setAcceptAllFileFilterUsed(false);
        if(arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            txtCaminhoArquivo.setText(arquivo.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btSelectArquivoActionPerformed

    private void btImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImportarActionPerformed
        
        ControleArquivoReclamacao importar = new ControleArquivoReclamacao();
        
        try {
            importar.Reclamacao(txtCaminhoArquivo.getText());
        } catch (IOException ex) {
            Logger.getLogger(ImportarServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        No primeiroNo = new No();
        primeiroNo = importar.getPrimeiroNo();
        
        
        while(primeiroNo != null){
            jTReclamacao.addRow(primeiroNo.getReclamacao());
            primeiroNo = primeiroNo.getNovoNo();
        }
        
        
    }//GEN-LAST:event_btImportarActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        
    }//GEN-LAST:event_btListarActionPerformed

    private void tblReclamacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReclamacaoMouseClicked
        // TODO add your handling code here:
        
        int id = tblReclamacao.getSelectedRow();
        

        String x = (String) tblReclamacao.getValueAt(id, 4);
        
        
        String ID;
        
        ID = ("0" + id);
        
        txtId.setText(x);
        
        
        
    }//GEN-LAST:event_tblReclamacaoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btImportar;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btSelectArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opQualidade;
    private javax.swing.JRadioButton opReclamacao;
    private javax.swing.JTable tblReclamacao;
    private javax.swing.JTextField txtCaminhoArquivo;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
